### ISSUE TITLE
When trying to generate qr-code locally 

### ISSUE THREAD

**Issue by adi-rebellion** [codemasher/nova-qrcode#1]
When trying to generate qr-code locally after taking the pull from the latest commit
Parse error: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /opt/lampp/htdocs/smiley-qr/vendor/chillerlan/php-qrcode/src/Data/QRMatrix.php on line 58

**Comment by codemasher** [comment]
This means that you're running a PHP version lower than 7.4 - the error is caused by a [typed property](https://www.php.net/manual/en/migration74.new-features.php).

**Comment by adi-rebellion** [comment]
No, Actually I m using PHP 7.4.3.
![PHP-V](https://user-images.githubusercontent.com/32679846/219371747-84e91bea-1d90-445c-8410-9e81b0dff479.png)

**Comment by codemasher** [comment]
The line that produces the error is this one: https://github.com/chillerlan/php-qrcode/blob/b6777fd58b2275ff108c75abc9fa9767b180a16b/src/Data/QRMatrix.php#L58 - it should run without issues on PHP 7.4 [as it does on CI](https://github.com/chillerlan/php-qrcode/actions/runs/4068533353).

**Comment by codemasher** [comment]
We've been there before: 
- https://github.com/chillerlan/php-qrcode/issues/43
- https://github.com/chillerlan/php-qrcode/discussions/119

btw. this is a private repo for the qrcode demo i'm running on my website. I'm going to move this issue to the qrcode  repo. (e: well, can't transfer it to org...))
