### ISSUE TITLE
HTTP 500 error when any QR requested 

### ISSUE THREAD

**Issue by andcl** [codemasher/nova-qrcode#2]
Inspecting devtools in https://smiley.codes/qrcode/, I get a 500 HTTP error when generating any QR.
Steps to reproduce:
- Load page
- Fill "Input String" with any text
- Click "Generate QR Code"

**Comment by codemasher** [comment]
Uh I updated some libraries a couple days ago and accidentally broke some things. I'm gonna fix it as soon as i can.

**Comment by codemasher** [comment]
This should be resolved with https://github.com/codemasher/nova-qrcode/commit/5c9e25573dc19686ceca27a0b9de21f11a50faf5

Please report back if you encounter any issues. Thank you!
